name: sistema_x

environment:
  sdk: '>=2.10.0 < 3.0.0'

dependencies:
  angel3_auth: ^4.0.0
  angel3_configuration: ^4.1.0 
  angel3_framework: ^4.2.0
  angel3_jael: ^4.2.0
  angel3_production: ^3.1.0
  angel3_static: ^4.1.0
  angel3_validate: ^4.0.0
  belatuk_pretty_logging: ^4.0.0

  fluent_query_builder: ^3.0.1
  
  sistema_x_core:
    path: ../sistema_x_core

dev_dependencies:
  angel3_hot: ^4.2.0
  angel3_test: ^4.0.0
  io: ^1.0.0
  test: ^1.17.5
  lints: ^1.0.0
